import {Link} from 'react-router';
import {useApi} from '../lib/useApi';
import Icon from '../components/ui/Icon';
import {CardSkeleton} from '../components/explore/ExploreCard';
export default function HomePage(){
 const {data,loading,error}=useApi('/posts?limit=4');
 const posts=data?.posts||[];
 const featured=posts[0];
 return <main className="vv-home mx-auto w-full max-w-[1500px] px-6 pb-20 lg:px-10">
  <section className="vv-home-hero">
   <div className="vv-home-intro"><p className="vv-home-eyebrow"><span/> A HOME FOR EXTRAORDINARY WORLDS</p><h1>Built block<br/>by block.<br/><em>Kept forever.</em></h1><p className="vv-home-description">Great worlds start with a little imagination. Discover remarkable builds, share the story behind yours, and give your creations a place to belong.</p><div className="flex flex-wrap gap-3"><Link to="/explore" className="vv-home-primary">Enter the archive <Icon name="arrowUpRight"/></Link><Link to="/create" className="vv-home-secondary">Share a creation <Icon name="plus"/></Link></div><div className="vv-home-note"><Icon name="cube"/><span>YOUR IDEAS. YOUR WORLDS. YOUR VAULT.</span></div></div>
   <div className="vv-home-visual"><div className="vv-home-orbit"/>{featured?<Link to={`/creations/${featured.id}`} className="vv-home-feature"><img src={featured.image} alt={featured.alt||featured.title} fetchPriority="high"/><div className="vv-home-feature-top"><span>FROM THE COMMUNITY</span><Icon name="arrowUpRight"/></div><div className="vv-home-feature-caption"><span>{featured.category}</span><h2>{featured.title}</h2><p>By {featured.creator}</p></div></Link>:<div className="vv-home-empty" aria-busy={loading}><Icon name="cube" className="!h-32 !w-32"/><p>{loading?'Opening the archive…':'A world of possibility.'}</p></div>}<span className="vv-home-coordinate">VOXELVAULT / SPATIAL ARCHIVE — 01</span></div>
  </section>
  <section className="vv-home-principles" aria-label="Your creative archive">{[['compass','Discover something extraordinary','Explore the details, find a new perspective, and meet the creators behind every world.'],['image','Tell the whole story','Bring your builds to life with galleries, descriptions, and credit where it belongs.'],['archive','Make space for your ideas','Keep your post images and private build files together in your own creative vault.']].map(([icon,title,text],i)=><article key={icon}><span className="vv-home-number">0{i+1} / <Icon name={icon}/></span><h2>{title}</h2><p>{text}</p></article>)}</section>
  <section className="py-16"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="vv-home-eyebrow">THE LATEST ADDITIONS</p><h2 className="mt-3 text-3xl font-headline-lg sm:text-4xl">Worlds worth getting lost in.</h2></div><Link to="/explore" className="inline-flex items-center gap-2 text-sm text-primary">Explore all creations <Icon name="arrowUpRight"/></Link></div>{error?<p className="text-on-surface-variant">The archive is temporarily unavailable. Please try Explore again shortly.</p>:<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{loading?Array.from({length:4},(_,i)=><CardSkeleton key={i}/>):posts.map(post=><Link key={post.id} to={`/creations/${post.id}`} className="vv-home-card"><div><img src={post.image} alt={post.alt||post.title} loading="lazy"/></div><p>{post.category}</p><h3>{post.title}</h3><span>By {post.creator}</span></Link>)}</div>}{!loading&&!error&&!posts.length&&<p className="text-on-surface-variant">The archive is ready for its first creation. Make it yours.</p>}</section>
  <section className="vv-home-invitation"><div><p className="vv-home-eyebrow">EVERY BLOCK HAS A STORY</p><h2>What will you build next?</h2><p>Your next idea deserves a place in the vault.</p></div><Link to="/create" className="vv-home-primary">Create your post <Icon name="plus"/></Link></section>
 </main>;
}
